// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9PvWakzaH1b8E31ZWBQ-98yde6RVO7GY',
    appId: '1:735043463564:web:462a6bf144abe0a82d0ea9',
    messagingSenderId: '735043463564',
    projectId: 'anindyapotofolio',
    authDomain: 'anindyapotofolio.firebaseapp.com',
    storageBucket: 'anindyapotofolio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Faz5H11K3GE4ABm2Yr9GWcyBV0O2csI',
    appId: '1:735043463564:android:81b3c3c96c5ef12c2d0ea9',
    messagingSenderId: '735043463564',
    projectId: 'anindyapotofolio',
    storageBucket: 'anindyapotofolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzWifbgDfECUDFQwAyqt4ZGj1kHy39ofo',
    appId: '1:735043463564:ios:fc2e4294aa001d772d0ea9',
    messagingSenderId: '735043463564',
    projectId: 'anindyapotofolio',
    storageBucket: 'anindyapotofolio.firebasestorage.app',
    iosBundleId: 'com.example.portofolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzWifbgDfECUDFQwAyqt4ZGj1kHy39ofo',
    appId: '1:735043463564:ios:fc2e4294aa001d772d0ea9',
    messagingSenderId: '735043463564',
    projectId: 'anindyapotofolio',
    storageBucket: 'anindyapotofolio.firebasestorage.app',
    iosBundleId: 'com.example.portofolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9PvWakzaH1b8E31ZWBQ-98yde6RVO7GY',
    appId: '1:735043463564:web:4f9c03dc0960588c2d0ea9',
    messagingSenderId: '735043463564',
    projectId: 'anindyapotofolio',
    authDomain: 'anindyapotofolio.firebaseapp.com',
    storageBucket: 'anindyapotofolio.firebasestorage.app',
  );
}
